version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - exam-net

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - exam-net
    depends_on:
      - backend

networks:
  exam-net:
